In [18]:
import numpy as np
from __future__ import division

Model:  
$y = 2x_1 + 3x_2$

In [30]:
# X is the matrix of 4 data points.
X = np.matrix([[3,4], [2,5], [4,2], [1,1]])
X

matrix([[3, 4],
        [2, 5],
        [4, 2],
        [1, 1]])

In [15]:
# y = Xb
# y(4x1) = X(4x2) b(2x1) [with dimension shown]

# b is the vector of coefficients
b = np.matrix([2,3]).transpose()
b

matrix([[2],
        [3]])

In [16]:
y = X*b

In [17]:
y

matrix([[18],
        [19],
        [14],
        [ 5]])

In [21]:
# w is the estimated coefficients.
w = np.matrix([1.8, 3.1]).transpose()
X*w

matrix([[ 17.8],
        [ 19.1],
        [ 13.4],
        [  4.9]])

In [33]:
err = (X*w - y)
err

matrix([[-0.2],
        [ 0.1],
        [-0.6],
        [-0.1]])

In [28]:
sq_err = err.transpose()*err # How you get the square of the vector's norm
sq_err

matrix([[ 0.42]])

Summary:  
$e = Xw - y$  
$\|e\|^2 = e^Te$

### WOLS ###
Now let us try to work with weighted OLS:  
$loss = \frac{1}{2}\sum_{i=1}^{n} (weight_i  (X_iW - y_i)^2)$

In [35]:
# weight is the vector of weight, one for each data point
err

matrix([[-0.2],
        [ 0.1],
        [-0.6],
        [-0.1]])