# Multi-Model Recommender

Assume we have 5 users and 6 products.

Matrix A will be the purchase history matrix

In [73]:
import numpy as np

A = np.matrix([[1,0,1,0,0,0], [1,0,1,0,1,0], [0,1,1,1,0,0], [0,1,0,1,0,1], [0,0,0,0,0,0]]) # History of purchase
A

matrix([[1, 0, 1, 0, 0, 0],
        [1, 0, 1, 0, 1, 0],
        [0, 1, 1, 1, 0, 0],
        [0, 1, 0, 1, 0, 1],
        [0, 0, 0, 0, 0, 0]])

##Users who did the same things

In the following examples, each value in the vector represents the total # of items the user has purchased from the specified product mix.

In [74]:
print "Item 3:", (A * np.matrix([0,0,1,0,0,0]).transpose()).tolist() # Call .tolist() just for ease of viewing

Item 3: [[1], [1], [1], [0], [0]]


In [75]:
print "Item 4:", (A * np.matrix([0,0,0,1,0,0]).transpose()).tolist() 

Item 4: [[0], [0], [1], [1], [0]]


In [76]:
print "Item 3 and 4:", (A * np.matrix([0,0,1,1,0,0]).transpose()).tolist() 

Item 3 and 4: [[1], [1], [2], [1], [0]]


In [77]:
print "Item 1 and 3:", (A * np.matrix([1,0,1,0,0,0]).transpose()).tolist() 

Item 1 and 3: [[2], [2], [1], [0], [0]]


## Co-occurrence matrix

A'A is the co-occurence matrix. It is an items x items matrix.  Each value represents the number of times two items co-occur (ignore the diagnoal values)

Examples:
- item 1 and item 3 co-occur twice (in user1 and user2)
- item 2 and item 4 co-occur twice (in user3 and user5)

In [91]:
print "Purchase History:\n", A, "\n"

AtA = A.transpose() * A
np.fill_diagonal(AtA, 0) # Fill the diagnonal with zeros, as they should be ignored.
print "Co-occurrence Matrix:"
print AtA, "\n"

Purchase History:
[[1 0 1 0 0 0]
 [1 0 1 0 1 0]
 [0 1 1 1 0 0]
 [0 1 0 1 0 1]
 [0 0 0 0 0 0]] 

Co-occurrence Matrix:
[[0 0 2 0 1 0]
 [0 0 1 2 0 1]
 [2 1 0 1 1 0]
 [0 2 1 0 0 1]
 [1 0 1 0 0 0]
 [0 1 0 1 0 0]] 



**Simple user-centric recommendation**

If a user is viewing item 1, what should we recommend?

In [92]:
h = np.matrix([1,0,0,0,0,0])
r = h * AtA  # Note: AtA * h' will produce the same result
print r

[[0 0 2 0 1 0]]


The above result (ignore item 1) tells us that we should recommend item 3, and then item 5.  It's based on the co-occurrence matrix:
- Two people who purchased item 1 also purchased item 3.
- One person who purchased item 1 also purchased item 5

This is similar to the "people who purchased this also purchase" list.

Now let's say a user comes in, and in her history she has purchased item 1 and item 2 in the past.  What should we recommend?

In [95]:
print "Purchase History:\n", A, "\n"
p = np.matrix([1,1,0,0,0,0])
print "History: item 1 and item 2; recommendation:\n", p * AtA 

Purchase History:
[[1 0 1 0 0 0]
 [1 0 1 0 1 0]
 [0 1 1 1 0 0]
 [0 1 0 1 0 1]
 [0 0 0 0 0 0]] 

History: item 1 and item 2; recommendation:
[[0 0 3 2 1 1]]


Let's look at the result (ignore item 1 and item 2).  We should recommend item 3, 4 and 5 (in that order).

Try one more time with user's history = item 1 and item 5.

In [96]:
print "Purchase History:\n", A, "\n"
p = np.matrix([1,0,0,0,1,0])
print "History: item 1 and item 5; recommendation:\n", p * AtA 

Purchase History:
[[1 0 1 0 0 0]
 [1 0 1 0 1 0]
 [0 1 1 1 0 0]
 [0 1 0 1 0 1]
 [0 0 0 0 0 0]] 

History: item 1 and item 5; recommendation:
[[1 0 3 0 1 0]]


##Cross Co-occurrence##

In addition to purchase history, we also have Bookmark history of the 6 products.

*Recommend a purchase based on bookmark history*

In [101]:
print "Purchase History:\n", A, "\n"

B = np.matrix([[0,0,0,1,0,0], [0,0,0,1,0,0], [0,1,0,0,0,0], [0,1,0,0,0,0], [1,0,0,0,1,1]]) # History of bookmark
print "Bookmark History:\n", B, "\n"
BtA = B.transpose() * A

print "Bookmark: 4  -", np.matrix([0,0,0,1,0,0]) * BtA
print "Bookmark: 2  -",  np.matrix([0,1,0,0,0,0]) * BtA
print "Bookmark: 1  -",  np.matrix([1,0,0,0,0,0]) * BtA
print "Bookmark: 6  -",  np.matrix([0,0,0,0,0,1]) * BtA
print "Bookmark: 1&2-",  np.matrix([1,1,0,0,0,0]) * BtA

Purchase History:
[[1 0 1 0 0 0]
 [1 0 1 0 1 0]
 [0 1 1 1 0 0]
 [0 1 0 1 0 1]
 [0 0 0 0 0 0]] 

Bookmark History:
[[0 0 0 1 0 0]
 [0 0 0 1 0 0]
 [0 1 0 0 0 0]
 [0 1 0 0 0 0]
 [1 0 0 0 1 1]] 

Bookmark: 4  - [[2 0 2 0 1 0]]
Bookmark: 2  - [[0 2 1 2 0 1]]
Bookmark: 1  - [[0 0 0 0 0 0]]
Bookmark: 6  - [[0 0 0 0 0 0]]
Bookmark: 1&2- [[0 2 1 2 0 1]]


Please note that in the last three cases, only user 5 have bookmarked product 1 and 5. But since he hasn't purchased any item, so we **cannot** correlate those two bookmarks to any purchase, and thus they have **no** effect on the recommendation. 

###Recommend a purchase based on both purchase history and bookmark history

In [110]:
print "Purchase History:\n", A, "\n"
print "Bookmark History:\n", B, "\n"

p = np.matrix([1,0,1,0,0,0])
b = np.matrix([0,1,0,0,0,0])
r = p*AtA + b*BtA
print "Purchase history:", p
print "Recommendations: ", p*AtA, "\n"
print "Bookmark history:", b
print "Recommendations: ", b*BtA, "\n"
print "Combined:        ", p*AtA + b*BtA, "\n"


Purchase History:
[[1 0 1 0 0 0]
 [1 0 1 0 1 0]
 [0 1 1 1 0 0]
 [0 1 0 1 0 1]
 [0 0 0 0 0 0]] 

Bookmark History:
[[0 0 0 1 0 0]
 [0 0 0 1 0 0]
 [0 1 0 0 0 0]
 [0 1 0 0 0 0]
 [1 0 0 0 1 1]] 

Purchase history: [[1 0 1 0 0 0]]
Recommendations:  [[2 1 2 1 2 0]] 

Bookmark history: [[0 1 0 0 0 0]]
Recommendations:  [[0 2 1 2 0 1]] 

Combined:         [[2 3 3 3 2 1]] 

[[2 1 2 1 2 0]]
[[0 2 1 2 0 1]]


###What if we have users' gender information?

Let's say we have a new matrix, G, which record the gender information.  The columns represent Male and Female.

In [123]:
print "Purchase History:\n", A, "\n"
G = np.matrix([[1,0], [0,1], [0,1], [1,0], [0,1]])
print "Gender info:\n", G, "\n"

Purchase History:
[[1 0 1 0 0 0]
 [1 0 1 0 1 0]
 [0 1 1 1 0 0]
 [0 1 0 1 0 1]
 [0 0 0 0 0 0]] 

Gender info:
[[1 0]
 [0 1]
 [0 1]
 [1 0]
 [0 1]] 



*For a female customer, what should we recommend?*

In [129]:
GtA = G.transpose() * A
g = np.matrix([0,1])
print "For a female, we recommend: ", g * GtA

 For a female, we recommend:  [[1 1 2 1 1 0]]


### Recommend based on purchase history, bookmark history and gender info

In [132]:
print "Purchase History:\n", A, "\n"
print "Bookmark History:\n", B, "\n"
print "Gender info:\n", G, "\n"
print "Purchase history:", p
print "Recommendations: ", p*AtA, "\n"
print "Bookmark history:", b
print "Recommendations: ", b*BtA, "\n"
print "Gender:          ", g
print "Recommendations: ", g*GtA, "\n"

print "Combined (two):   ", p*AtA + b*BtA, "\n"
print "Combined (all):   ", p*AtA + b*BtA + g*GtA, "\n"


Purchase History:
[[1 0 1 0 0 0]
 [1 0 1 0 1 0]
 [0 1 1 1 0 0]
 [0 1 0 1 0 1]
 [0 0 0 0 0 0]] 

Bookmark History:
[[0 0 0 1 0 0]
 [0 0 0 1 0 0]
 [0 1 0 0 0 0]
 [0 1 0 0 0 0]
 [1 0 0 0 1 1]] 

Gender info:
[[1 0]
 [0 1]
 [0 1]
 [1 0]
 [0 1]] 

Purchase history: [[1 0 1 0 0 0]]
Recommendations:  [[2 1 2 1 2 0]] 

Bookmark history: [[0 1 0 0 0 0]]
Recommendations:  [[0 2 1 2 0 1]] 

Gender:           [[0 1]]
Recommendations:  [[1 1 2 1 1 0]] 

Combined (two):    [[2 3 3 3 2 1]] 

Combined (all):    [[3 4 5 4 3 1]] 



##Similar Items



In [111]:
print "Purchase History:\n", A, "\n"
print "Purchase co-occurrence:\n", AtA, "\n"

Purchase History:
[[1 0 1 0 0 0]
 [1 0 1 0 1 0]
 [0 1 1 1 0 0]
 [0 1 0 1 0 1]
 [0 0 0 0 0 0]] 

Purchase co-occurrence:
[[0 0 2 0 1 0]
 [0 0 1 2 0 1]
 [2 1 0 1 1 0]
 [0 2 1 0 0 1]
 [1 0 1 0 0 0]
 [0 1 0 1 0 0]] 



Take item 4 as an example.  

Its row in AtA is `[0 2 1 0 0 1]`.  So it occurs the most with item 2, and also with 3 and 6.  So items 2, 3 and 6 are similar to it (based on purchase history).  

We can obtain the same result by multiplying AtA with an item vector.

In [119]:
i = np.matrix([0,0,0,1,0,0])
i * AtA

matrix([[0, 2, 1, 0, 0, 1]])

So i * AtA produces the "similar item" vector based on just the purchase history.

What if we use both purchase history and bookmark history?

In [120]:
print "Purchase History:\n", A, "\n"
print "Bookmark History:\n", B, "\n"
print "Items similar to 4, based on purchase:\n", i * AtA, "\n"
print "Items similar to 4, based on purchase and bookmarks:\n", i * AtA + i * BtA, "\n"

Purchase History:
[[1 0 1 0 0 0]
 [1 0 1 0 1 0]
 [0 1 1 1 0 0]
 [0 1 0 1 0 1]
 [0 0 0 0 0 0]] 

Bookmark History:
[[0 0 0 1 0 0]
 [0 0 0 1 0 0]
 [0 1 0 0 0 0]
 [0 1 0 0 0 0]
 [1 0 0 0 1 1]] 

Items similar to 2, based on purchase:
[[0 2 1 0 0 1]] 

Items similar to 2, based on purchase and bookmarks:
[[2 2 3 0 1 1]] 

